# Generated by Django 3.1.3 on 2020-12-05 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Express',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='物流名称')),
                ('mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='输入的电话号码格式不对', regex='^[0-9]{8,11}$')], verbose_name='电话号码')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='物流地址')),
                ('comment', models.CharField(blank=True, max_length=200, verbose_name='物流描述')),
            ],
        ),
    ]
