# Generated by Django 3.1.3 on 2020-12-05 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='用户昵称')),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=10, verbose_name='性别')),
                ('vip_level', models.CharField(choices=[('one', '非会员'), ('two', '普通会员'), ('three', '超级会员')], default='非会员', max_length=10, verbose_name='会员星级')),
                ('balance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='余额')),
                ('username', models.CharField(max_length=200, verbose_name='用户名')),
                ('password', models.CharField(max_length=200, verbose_name='密码')),
                ('mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='输入的电话号码格式不对', regex='^[0-9]{8,11}$')], verbose_name='电话号码')),
                ('address', models.TextField(blank=True, verbose_name='住址')),
            ],
        ),
    ]
