# Generated by Django 3.1.3 on 2020-12-05 13:47

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='超市名称')),
                ('start_time', models.TimeField(default=django.utils.timezone.now, verbose_name='起始营业时间')),
                ('end_time', models.TimeField(default=django.utils.timezone.now, verbose_name='结束营业时间')),
                ('mobile_number', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator(message='输入的电话号码格式不对', regex='^[0-9]{8,11}$')], verbose_name='电话号码')),
                ('address', models.TextField(blank=True, verbose_name='超市地址')),
            ],
        ),
    ]
