# Generated by Django 3.1.3 on 2020-12-05 13:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='活动名称')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='活动起始时间')),
                ('end_date', models.DateField(default=django.utils.timezone.now, verbose_name='活动结束时间')),
                ('comment', models.CharField(max_length=200, verbose_name='活动描述')),
            ],
        ),
    ]
