# Generated by Django 3.1.3 on 2020-12-05 13:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='商品名称')),
                ('price', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='商品价格')),
                ('production_date', models.DateField(default=django.utils.timezone.now, verbose_name='生产日期')),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='商品数量')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.category', verbose_name='所属品类')),
            ],
        ),
    ]
