# Generated by Django 3.1.3 on 2020-12-06 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
        ('supermarket', '0001_initial'),
        ('supplier', '0001_initial'),
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='supermarket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supermarket.supermarket', verbose_name='所属超市'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name='供货商'),
        ),
        migrations.AddField(
            model_name='commodity',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='warehouse.warehouse', verbose_name='贮存仓库'),
        ),
    ]
