# Generated by Django 3.1.3 on 2020-12-06 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('commodity', '0002_auto_20201206_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier', verbose_name='供货商'),
        ),
    ]
