# Generated by Django 3.1.3 on 2020-12-23 09:38

import commodity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_auto_20201206_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=commodity.models.user_directory_path, verbose_name='照片'),
        ),
    ]
