# Generated by Django 3.1.3 on 2020-12-05 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supermarket', '0001_initial'),
        ('department', '0003_auto_20201205_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='supermarket',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supermarket.supermarket', verbose_name='所属超市'),
        ),
    ]
